import Link from 'next/link'

const g = {
  fontFamily: 'system-ui, -apple-system, sans-serif',
  background: 'linear-gradient(160deg, #2D1005 0%, #0D0400 40%, #000000 100%)',
  color: '#fff',
  minHeight: '100vh',
}
const wrap = { maxWidth: 760, margin: '0 auto', padding: '4rem 1.5rem 5rem' }

export const metadata = { title: 'Terms & Conditions — Athlete Planner' }

export default function TermsPage() {
  return (
    <div style={g}>
      <div style={wrap}>
        <Link href="/" style={{ fontSize: 13, color: '#CF6232', textDecoration: 'none', display: 'inline-block', marginBottom: 32 }}>
          ← Back to Athlete Planner
        </Link>
        <h1 style={{ fontSize: 'clamp(26px, 5vw, 38px)', fontWeight: 800, letterSpacing: '-1px', marginBottom: 8 }}>
          Terms & Conditions
        </h1>
        <p style={{ fontSize: 13, color: 'rgba(255,255,255,0.35)', marginBottom: 48 }}>
          Last updated: June 2026
        </p>

        <Section title="The service">
          <P>Athlete Planner provides AI-generated personalised training plans delivered as Google Sheets files to your email address. Plans are generated using Anthropic's Claude AI based on the information you provide in our quiz.</P>
        </Section>

        <Section title="Payment">
          <P>The service is available for a one-time payment. There is no subscription, no recurring charge, and no hidden fees. Payment is processed securely by Stripe. You will receive access to your plan immediately after successful payment.</P>
          <P>Current pricing: €14.97 for a training plan; €19.97 for a training plan with a personalised nutrition guide.</P>
        </Section>

        <Section title="Refund policy">
          <P>Under EU consumer law, you have the right to withdraw from a purchase within 14 days without giving a reason.</P>
          <P>However, by requesting immediate delivery of your digital plan upon purchase, you acknowledge that the right of withdrawal may be lost once the plan has been generated and delivered to your email. Refund requests made after delivery are assessed at Athlete Planner's discretion.</P>
          <P>To request a refund, contact <a href="mailto:athleteplanner.app@gmail.com" style={{ color: '#CF6232' }}>athleteplanner.app@gmail.com</a> with your order details.</P>
        </Section>

        <Section title="Disclaimer">
          <P>Training plans generated by Athlete Planner are produced by artificial intelligence and are intended for informational purposes only. They are not a substitute for professional coaching, sports medicine advice, or medical supervision.</P>
          <P>You should consult a qualified professional before starting any new training programme, particularly if you have existing injuries, medical conditions, or have been inactive. Athlete Planner accepts no liability for injuries, health complications, or other damages resulting from following a generated plan.</P>
          <P>Always train within your own limits and stop if you experience pain or discomfort.</P>
        </Section>

        <Section title="Intellectual property">
          <P>The training plan generated for you is licensed for your personal use only. You may not resell, redistribute, or use it commercially without prior written permission from Athlete Planner.</P>
        </Section>

        <Section title="Availability">
          <P>We aim to maintain continuous availability of the service but cannot guarantee uninterrupted access. We are not liable for losses resulting from service downtime or delays in plan delivery.</P>
        </Section>

        <Section title="Governing law">
          <P>These terms are governed by the laws of Spain. Any disputes shall be subject to the exclusive jurisdiction of the courts of Spain.</P>
        </Section>

        <Section title="Contact">
          <P>For any questions about these terms, contact <a href="mailto:athleteplanner.app@gmail.com" style={{ color: '#CF6232' }}>athleteplanner.app@gmail.com</a>.</P>
        </Section>
      </div>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40, paddingBottom: 40, borderBottom: '1px solid rgba(255,255,255,0.07)' }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: '#CF6232', marginBottom: 14, letterSpacing: '-0.3px' }}>{title}</h2>
      {children}
    </section>
  )
}

function P({ children }: { children: React.ReactNode }) {
  return <p style={{ fontSize: 15, color: 'rgba(255,255,255,0.65)', lineHeight: 1.75, margin: '0 0 12px' }}>{children}</p>
}
